[env:receiver]
platform  = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board     = seeed_xiao_esp32c6
framework = arduino

; MAC: 58:e6:c5:1b:9d:04  (COM16 — physical label: RECEIVER)
upload_port   = COM16
monitor_port  = COM16

; zigbee_zczr.csv = Coordinator/Router partition layout
board_build.partitions = zigbee_zczr.csv

build_flags =
    -DZIGBEE_MODE_ZCZR
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DZIGBEE_CHANNEL=15

monitor_speed = 115200
upload_speed  = 921600
