[env:sender]
platform  = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board     = seeed_xiao_esp32c6
framework = arduino

; MAC: 58:e6:c5:19:c0:08  (COM15 — physical label: SENDER)
upload_port   = COM15
monitor_port  = COM15

; zigbee.csv = End Device partition layout (no OTA slot)
board_build.partitions = zigbee.csv

build_flags =
    -DZIGBEE_MODE_ED
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DZIGBEE_CHANNEL=15

monitor_speed = 115200
upload_speed  = 921600

[env:sender2]
platform  = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board     = seeed_xiao_esp32c6
framework = arduino

; MAC: 58:e6:c5:1a:7a:08  (COM18 — DS2413 board)
upload_port   = COM18
monitor_port  = COM18

board_build.partitions = zigbee.csv

build_flags =
    -DZIGBEE_MODE_ED
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DZIGBEE_CHANNEL=15

lib_deps = paulstoffregen/OneWire

monitor_speed = 115200
upload_speed  = 921600
